; This file was auto-generated by drush make
core = 6.x

api = 2
projects[drupal][version] = "6.22"
projects[drupal][download][type] = "get"
projects[drupal][download][url] = "http://openatrium.com/sites/openatrium.com/files/atrium_releases/atrium-1-0.tgz"

; Modules
projects[honeypot][version] = "1.13"
